apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guard-pb-data
  namespace: guard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
