apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: guard
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: guard
      images:
        - alias: guard
          imageName: ghcr.io/barakplasma/guard-app:main
          commonUpdateSettings:
            updateStrategy: digest
            pullSecret: pullsecret:argocd/ghcr-pull
            platforms:
              - linux/arm64
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
