apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/barakplasma/guard.git
    targetRevision: main
    path: charts/guard
    helm:
      releaseName: guard
  destination:
    server: https://kubernetes.default.svc
    namespace: guard
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
